
export enum FormFieldTypes {
    FLD_TYPE_TEXT = 'FLD_TYPE_TEXT',
    FLD_TYPE_AVATAR = 'FLD_TYPE_AVATAR',
    FLD_TYPE_EMAIL = 'FLD_TYPE_EMAIL',
    FLD_TYPE_NUMBER = 'FLD_TYPE_NUMBER',
    FLD_TYPE_PHONE = 'FLD_TYPE_PHONE',
    FLD_TYPE_TEXTAREA = 'FLD_TYPE_TEXTAREA',
    FLD_TYPE_OPTION = 'FLD_TYPE_OPTION',
    FLD_TYPE_OPTION_MULTI = 'FLD_TYPE_OPTION_MULTI',
    FLD_TYPE_SWITCH = 'FLD_TYPE_SWITCH',
    FLD_TYPE_RICH_TEXT = 'FLD_TYPE_RICH_TEXT',
    FLD_TYPE_FILE = 'FLD_TYPE_FILE',
    FLD_TYPE_FILE_MULTI = 'FLD_TYPE_FILE_MULTI',
    FLD_TYPE_DATE = 'FLD_TYPE_DATE',
    FLD_TYPE_TIME = 'FLD_TYPE_TIME',
    FLD_TYPE_DATE_TIME = 'FLD_TYPE_DATE_TIME',
 }
 
export const FormFieldTypesList = Object.values(FormFieldTypes);